### ISSUE TITLE
Doesn't handle narrowing buffers properly.

### ISSUE THREAD

**Issue by TeMPOraL** [emacsorphanage/swoop#12]
Swoop seems to be scrolling the searched buffer according to detected line number. In case it's a narrowed buffer, the line numbers don't match the actual content, so target buffer is scrolled to invalid lines.

Example:
- Create a buffer with following contents:

```
asdf

asdf

maka paka

asdf

aff aff


asdf
```
- Narrow to region between the second `asdf` (inclusive) and `aff aff` (inclusive).
- Execute `swoop` for `asdf`.

You'll see that not only line numbers don't match, but also it detects only one instance of `asdf`, even though the narrowed part contains two.

**Comment by syohex** [comment]
Could you try [this patch](https://gist.githubusercontent.com/syohex/b5f9bf829e0f5835a7e82cb078c755d0/raw/e6f86973e0ba75015e90b3f9c01a6c3431dc201c/swoop-narrow.diff) ?

https://gist.github.com/syohex/b5f9bf829e0f5835a7e82cb078c755d0
