### ISSUE TITLE
Swoop seems to disable nlinum mode in swooped buffer on exit.

### ISSUE THREAD

**Issue by TeMPOraL** [emacsorphanage/swoop#13]
1. Disable `linum-mode` and enable `nlinum-mode` in a buffer.
2. Execute `swoop`, searching for an existing string.
3. Press ENTER on a match.

You'll see `nlinum-mode` getting disabled, i.e. line numeration disappearing from the searched buffer.

**Comment by syohex** [comment]
No. nlinum-mode is not disabled after `swoop` command. Because value of `nlinum-mode` is still `t`  despite line numbers are disappeared.

You can call nlinum updating function manually as below.

```lisp
(advice-add 'swoop-action-goto-target-point
            :before (lambda (&rest args)
                      (run-with-timer 1 nil #'nlinum--setup-windows)))
```
