### ISSUE TITLE
helm-swoop

### ISSUE THREAD

**Issue by Gahamelas** [emacsorphanage/swoop#19]
What is the main difference between these packages? Thanks.

**Comment by conao3** [comment]
- https://melpa.org/#/swoop
- https://melpa.org/#/helm-swoop

`helm-swoop` requires `helm`, but `swoop` not.

**Comment by Gahamelas** [comment]
So basically they are identical in their functionality.

**Comment by conao3** [comment]
Yes, But, As `helm-swoop` is well maintained and has a lot of users, we recommend using `helm-swoop`.

**Comment by Gahamelas** [comment]
What I like about swoop is the formatting. Do you know if we can get the same highlighting, etc. in helm-swoop (whether it is customizable)?

**Comment by conao3** [comment]
I don't know.

Customizing below faces is not satisfy your intention?
```elisp
(defface helm-swoop-target-line-face
  '((t (:background "#e3e300" :foreground "#222222")))
  "Face for helm-swoop target line"
  :group 'helm-swoop)
(defface helm-swoop-target-line-block-face
  '((t (:background "#cccc00" :foreground "#222222")))
  "Face for target line"
  :group 'helm-swoop)
(defface helm-swoop-target-word-face
  '((t (:background "#7700ff" :foreground "#ffffff")))
  "Face for target word"
  :group 'helm-swoop)
(defface helm-swoop-line-number-face
  '((t (:foreground "#999999")))
  "Face for line numbers"
  :group 'helm-swoop)
```

**Comment by Gahamelas** [comment]
For some reason this does not have an effect when I add it in my init.el and restart emacs.

**Comment by conao3** [comment]
OK, let's move your helm-swoop open issue (emacsorphanage/helm-swoop/issues/189)
