### ISSUE TITLE
[Feature Request] swoop-function feature

### ISSUE THREAD

**Issue by pbmtp** [emacsorphanage/swoop#4]
Hi,

First thanks for emacs-swoop it is a nice extension.

Would it be possible to implement a "swoop functions of current buffers" using informations from tags (gtags and others) or semantic ?

This could be used for example as a remplacement of eassist (from cedet) for fast browsing to function of current C buffer.

Thanks in advance

**Comment by tarsius** [comment]
Closing because of

> This package is deprecated and we suggest to move [helm-swoop](https://github.com/emacsorphanage/helm-swoop) instead. [helm-swoop](https://github.com/emacsorphanage/helm-swoop) is the successor to swoop and is well maintained.

> There are no additional feature updates and it is a low priority for bugs to be fixed.
