### ISSUE TITLE
swoop doesn't warn when editing read only buffers

### ISSUE THREAD

**Issue by hyOzd** [emacsorphanage/swoop#8]
When I try to edit a RO buffer with swoop, it switches to edit mode with no warning. You can edit the text in swoop buffer, but of course changes are not reflected in the target buffer. A message appears in minibuffer saying something like "Buffer somebuffername is read only!".

I would expect swoop to not to switch edit mode (with a warning) when target buffer is read only, or maybe ask something like:

"Do you want to disable Read Only mode? [y/n]"

**Comment by conao3** [comment]
Thanks suggestion!
